FROM golang:1.19

ARG app_name

RUN apt-get update && apt-get install -y wget && apt-get install -y brotli && apt-get install -y gzip

RUN	wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 \
    && chmod +x tailwindcss-linux-x64 \
    && mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss

RUN mkdir -p /go/src/github.com/BlackMocca/go-lightweight-scheduler-ui
WORKDIR /go/src/github.com/BlackMocca/go-lightweight-scheduler-ui

ENV GO111MODULE=on
ENV ADDR=0.0.0.0
ENV TZ=Asia/Bangkok

# Copy app service 
RUN mkdir -p build/web/resources
COPY resources build/web

COPY go.mod .
COPY . .

RUN go mod tidy     

RUN cd tailwind && tailwindcss -i ./tailwind-min.css -o ../resources/styles/tailwind/tailwind-min.css --minify
RUN mkdir -p build/web/resources && cp -r resources build/web
RUN GOARCH=wasm GOOS=js go build -ldflags="-s -w" -a -installsuffix cgo -o ./build/web/app.wasm main.go
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -a -installsuffix cgo -o  ./build/app main.go

## OPTIMIZE WASM
RUN wget https://github.com/WebAssembly/binaryen/releases/download/version_119/binaryen-version_119-x86_64-linux.tar.gz \
    && tar -xvzf binaryen-version_119-x86_64-linux.tar.gz
RUN ./binaryen-version_119/bin/wasm-opt -Oz ./build/web/app.wasm -o ./build/web/app.wasm
RUN brotli -q 11 --force ./build/web/app.wasm -o ./build/web/app.wasm.br
RUN gzip -9 --keep --force ./build/web/app.wasm

FROM alpine:latest 
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /usr/app

ARG app_name
ARG build_number
ARG version
ENV env_build_number=${build_number}
ENV env_version=${version}
ENV ADDR=0.0.0.0
ENV TZ=Asia/Bangkok

COPY --from=0 /go/src/github.com/BlackMocca/go-lightweight-scheduler-ui/build .

EXPOSE 8080

CMD ["./app"]  

