FROM golang:1.19

ARG app_name
ARG build_number
ARG version
ENV env_build_number=${build_number}
ENV env_version=${version}
ENV GO111MODULE=on
ENV ADDR=0.0.0.0
ENV TZ=Asia/Bangkok

RUN mkdir -p /go/src/github.com/BlackMocca/go-lightweight-scheduler-ui
WORKDIR /go/src/github.com/BlackMocca/go-lightweight-scheduler-ui

# Move to project folder
WORKDIR /go/src/github.com/BlackMocca/go-lightweight-scheduler-ui

COPY . . 
RUN go get -u github.com/githubnemo/CompileDaemon
RUN go install github.com/githubnemo/CompileDaemon
RUN go mod tidy    

RUN GOARCH=wasm GOOS=js go build -o ./build/web/app.wasm main.go
RUN go build -o ./build/app main.go

EXPOSE 8080

ENTRYPOINT CompileDaemon -include=go.mod -log-prefix=false -color=true -build="make -B build" -command="make -B run" 
