version: "3"

services: 

  go-lightweight-scheduler-ui:
    build:
      context: ./
      dockerfile: ./Dockerfile-development
    container_name: go-lightweight-scheduler-ui
    env_file: .env
    networks: 
      - default
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/github.com/BlackMocca/go-lightweight-scheduler-ui
      - ./build:/go/src/github.com/BlackMocca/go-lightweight-scheduler-ui/build
    
networks:
  default:
    external:
      name: scheduler